name: qawolf

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          # chromium dependencies
          sudo apt-get install libgbm1
          # webkit dependencies
          sudo apt-get install libwoff1 libopus0 libwebp6 libwebpdemux2 libenchant1c2a libgudev-1.0-0 libsecret-1-0 libhyphen0 libgdk-pixbuf2.0-0 libegl1 libgles2 libevent-2.1-6 libnotify4 libxslt1.1

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - name: Start local server
        run: npx parcel src/index.html & npx wait-on http://localhost:1234

      - run: npx qawolf test
        env:
          QAW_ARTIFACT_PATH: ${{ github.workspace }}/artifacts

        #   # configure tests with environment variables
        #   # https://docs.qawolf.com/docs/configuration
        #   QAW_SLEEP_MS: 0
        #   # you can also use GitHub secrets for environment variables
        #   # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets
        #   LOGIN_PASSWORD: ${{ secrets.PASSWORD }}

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: qawolf
          path: ${{ github.workspace }}/artifacts
