name: qawolf
on:
  push:
    # test every branch
    # edit below if you only want certain branches tested
    branches: "*"
  # schedule:
  #   # test on schedule using cron syntax
  #   - cron: "0 * * * *" # every hour
jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - name: Start local server
        run: npx parcel src/index.html & npx wait-on http://localhost:1234

      - run: npx qawolf test
        env:
          QAW_ARTIFACT_PATH: ${{ github.workspace }}/artifacts

        #   # configure tests with environment variables
        #   # https://docs.qawolf.com/docs/configuration
        #   QAW_SLEEP_MS: 0
        #   # you can also use GitHub secrets for environment variables
        #   # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets
        #   LOGIN_PASSWORD: ${{ secrets.PASSWORD }}

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: qawolf
          path: ${{ github.workspace }}/artifacts
